name: Build & Test pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Add "id-token" with the intended permissions.
permissions:
  contents: "read"
  id-token: "write"
  pull-requests: write
  actions: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: src/
    steps:
      # Checkout current branch
      - name: Checkout
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/

      # Build the solution
      - name: Build
        run: dotnet build --no-restore
        working-directory: src/

      # Run tests and generate code coverage
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage

      - name: Merge Coverage Reports
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate Merged Coverage Report
        run: reportgenerator "-reports:coverage/**/coverage.cobertura.xml" "-targetdir:mergedcoveragereport" "-reporttypes:Html;Cobertura"

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "mergedcoveragereport/Cobertura.xml"
          badge: true
          format: "markdown"
          output: "both"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
